name: Nuxt 3 Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate Nuxt app
        run: npx nuxt generate

      - name: Deploy to GitHub Pages
        uses: JamesIves/deploy-pages@v1.7.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          force: true
          silent: false
